version: "3"
services:
  database:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    container_name: database
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
      MSSQL_PID: "Express"
